server:
    servlet:
        context-path: /api/
    port:
        9090
        
spring:
    profiles:
        active: postgresql
        
security:
    jwt:
        token:
            accessExpiration: 300000
            refreshExpiration: 3600000