# Init database
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/users_db
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop